name: branchname
on:
  workflow_dispatch:
  push:
    branches:
  pull_request:
    branches:
      - main

jobs:
  check_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Display GITHUB_REF
        run: echo "${GITHUB_REF}"
      - name: Display a possible tag
        run: echo "${GITHUB_REF/refs\/tags\//}" | sed '/refs/d'
      - name: Display GITHUB_REF_NAME
        run: echo "${GITHUB_REF_NAME}"
      - name: Get the branch name
        id: branch-name
        uses: tj-actions/branch-names@v6.4
      - name: Display the branch name
        run: echo "${{ steps.branch-name.outputs.current_branch }}"
      - name: Do we have a tag ?
        run: echo "${{ steps.branch-name.outputs.is_tag }}"
      - name: Display the tag
        run: echo "${{ steps.branch-name.outputs.tag }}"
